// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TicTacToe.Data;

#nullable disable

namespace TicTacToe.Data.Migrations
{
    [DbContext(typeof(TicTacToeContext))]
    [Migration("20260210153044_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TicTacToe.Data.Entity.GamesEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BoardState")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("board_state");

                    b.Property<int>("ConnectedPlayers")
                        .HasColumnType("integer")
                        .HasColumnName("connected_players");

                    b.Property<long?>("CurrentPlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("current_player_id");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<bool>("IsDraw")
                        .HasColumnType("boolean")
                        .HasColumnName("is_draw");

                    b.Property<DateTime?>("LastMoveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_move_at");

                    b.Property<long?>("PlayerOId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_o_id");

                    b.Property<long?>("PlayerXId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_x_id");

                    b.Property<string>("RoomCode")
                        .HasColumnType("text")
                        .HasColumnName("room_code");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<long?>("WinnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("winner_id");

                    b.HasKey("Id");

                    b.HasIndex("PlayerOId");

                    b.HasIndex("PlayerXId");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_games_status");

                    b.HasIndex("WinnerId");

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("TicTacToe.Data.Entity.MovesEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("GameId")
                        .HasColumnType("bigint")
                        .HasColumnName("game_id");

                    b.Property<short>("MoveNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("move_number");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("played_at");

                    b.Property<long?>("PlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_id");

                    b.Property<short>("Position")
                        .HasColumnType("smallint")
                        .HasColumnName("position");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("moves", (string)null);
                });

            modelBuilder.Entity("TicTacToe.Data.Entity.PlayersEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Draws")
                        .HasColumnType("integer")
                        .HasColumnName("draws");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("integer")
                        .HasColumnName("games_played");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Wins")
                        .HasColumnType("integer")
                        .HasColumnName("wins");

                    b.HasKey("Id");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("TicTacToe.Data.Entity.GamesEntity", b =>
                {
                    b.HasOne("TicTacToe.Data.Entity.PlayersEntity", "PlayerO")
                        .WithMany()
                        .HasForeignKey("PlayerOId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TicTacToe.Data.Entity.PlayersEntity", "PlayerX")
                        .WithMany()
                        .HasForeignKey("PlayerXId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TicTacToe.Data.Entity.PlayersEntity", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PlayerO");

                    b.Navigation("PlayerX");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("TicTacToe.Data.Entity.MovesEntity", b =>
                {
                    b.HasOne("TicTacToe.Data.Entity.GamesEntity", "Game")
                        .WithMany("Moves")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicTacToe.Data.Entity.PlayersEntity", "Player")
                        .WithMany("Moves")
                        .HasForeignKey("PlayerId");

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("TicTacToe.Data.Entity.GamesEntity", b =>
                {
                    b.Navigation("Moves");
                });

            modelBuilder.Entity("TicTacToe.Data.Entity.PlayersEntity", b =>
                {
                    b.Navigation("Moves");
                });
#pragma warning restore 612, 618
        }
    }
}
